### Numpy Practice(basic operation)

In [2]:
import numpy as np

How to show numpy <b><i>version</i></b> and <b><i>configuration</i></b>?

In [3]:
np.__version__
np.show_config()

'1.21.2'

#### 1. create a null vector of size 10

In [6]:
vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 2. how to find the memory size of any array?

In [7]:
matrix = np.zeros((10, 10))
print(matrix)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [8]:
print(f'{matrix.size*matrix.itemsize}')

800


In [9]:
matrix.size  # in numpy shape != size

100

#### 3. create a null vector of size 10 but the fifth value which is 1

In [10]:
z = np.zeros(10)
z[4] = 1  # indexing like operation in python
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4. create a vector with values ranging from 10 to 49

In [12]:
z = np.arange(10,50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5. how to reverse the array [ : :-1]

In [17]:
z = z[::-1]
z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 6. create a 3*3 matrix with value range from 0 to 8

In [18]:
matrix = np.arange(9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7. how to find non-zero elements from [1, 2, 0, 0, 0, 4, 0]

In [20]:
# the result will return index of the elements in vector
nz = np.nonzero([1, 2, 4, 0, 0, 4, 0])
nz 

(array([0, 1, 2, 5]),)

#### 8. how to create indentity matrix? 

In [22]:
z = np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. how to create a 3*3*3 matrix with random values, np.random.random()

In [25]:
matrix = np.random.random((3, 3, 3))
matrix

array([[[0.41499312, 0.5220125 , 0.18114917],
        [0.99245934, 0.30656982, 0.29646122],
        [0.53494359, 0.86974671, 0.89575307]],

       [[0.71063097, 0.73803335, 0.78325161],
        [0.67706664, 0.3143693 , 0.1577873 ],
        [0.01369556, 0.35894694, 0.8890076 ]],

       [[0.90344072, 0.32580495, 0.8713894 ],
        [0.23539688, 0.62048341, 0.15930957],
        [0.10272704, 0.20034875, 0.62444197]]])

#### 10. how to find the max, min value in the matrix

In [27]:
matrix_max, matrix_min = matrix.max(), matrix.min()
print(matrix_max, matrix_min)

0.9924593426174486 0.013695555616247912


#### 11. calculate the mean value of the vector

In [28]:
vector = np.random.random((1, 10))
print(vector)
print(vector.mean())

[[0.64151712 0.38481724 0.23107413 0.62979558 0.33818273 0.69388879
  0.50684822 0.09509645 0.43712579 0.56169571]]
0.4520041778586199


#### 12. how to add a border(filled with 0) around an existing array

In [30]:
z = np.ones((5, 5))
print(z)
z = np.pad(z, pad_width=1, mode='constant', constant_values=0) # use pad method
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 13. what is the result of the following expression

In [36]:
print(0*np.nan)
print(np.nan*np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3*0.1)

nan
nan
False
nan
True
False


#### 14. create 5*5 matrix with values 1, 2, 3, 4 just below the diagnol

In [40]:
z = np.diag(1+np.arange(4), k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 15. how to normalize a 5*5 random matrix

In [45]:
z = np.random.random((5, 5))
print(z)
print(np.mean(z))
print(z.mean()) # np.mean(m) = m.mean()
z = (z - z.mean())/(z.std())
Z = (z - np.mean (z)) / (np.std (z))
print(z)
print(Z)

[[0.72172877 0.11426814 0.94420626 0.83833375 0.23666329]
 [0.66914221 0.38727548 0.04448971 0.92106289 0.26150744]
 [0.29901011 0.38352573 0.15576189 0.70765583 0.5476919 ]
 [0.89329794 0.42957551 0.17205584 0.20949215 0.48857645]
 [0.72541707 0.65964175 0.53836729 0.92543309 0.74819899]]
0.5208951794600309
0.5208951794600309
[[ 0.72074789 -1.45929558  1.51917095  1.13921765 -1.02004615]
 [ 0.53202621 -0.47953191 -1.70971511  1.43611447 -0.93088593]
 [-0.79629704 -0.49298894 -1.31038359  0.67024316  0.09616757]
 [ 1.33647214 -0.32772633 -1.25190817 -1.11755741 -0.11598485]
 [ 0.73398437  0.49793112  0.06270359  1.45179816  0.81574371]]
[[ 0.72074789 -1.45929558  1.51917095  1.13921765 -1.02004615]
 [ 0.53202621 -0.47953191 -1.70971511  1.43611447 -0.93088593]
 [-0.79629704 -0.49298894 -1.31038359  0.67024316  0.09616757]
 [ 1.33647214 -0.32772633 -1.25190817 -1.11755741 -0.11598485]
 [ 0.73398437  0.49793112  0.06270359  1.45179816  0.81574371]]


#### 16. how to multiply 5*3 matrix by a 3*2 matrix(real matrix product)

In [46]:
z = np.dot(np.ones((5, 3)), np.ones((3, 2)))
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 17. how to convert a float(32 bits) array into an integer (32bits) in place?

In [47]:
z = np.arange(10, dtype=np.float32)
z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [48]:
z = z.astype(np.int32, copy=False)
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### 18. how to substract the mean of each row of a matrix?


In [52]:
x = np.random.rand(5, 10)
y = x - x.mean(axis=1, keepdims=True)
print(y)

[[ 0.09282566  0.43270403 -0.41988072  0.00135532 -0.26029707  0.43597539
  -0.26641621 -0.15806081 -0.32327851  0.46507291]
 [ 0.21233217 -0.42637361  0.19279923  0.01761732  0.15637257 -0.39175031
   0.17545321 -0.05727942  0.33978558 -0.21895675]
 [-0.13985007 -0.01013031 -0.38653358 -0.07052227  0.19989556 -0.05166072
  -0.05410807  0.17349746  0.40951314 -0.07010115]
 [ 0.25492601 -0.2511949   0.14909361  0.52359656  0.3954488  -0.32554481
  -0.39492572 -0.27240278 -0.14343996  0.06444319]
 [ 0.31901021 -0.52003354 -0.50346572 -0.45939038  0.37029971 -0.08093508
   0.19863078 -0.07167328  0.2820408   0.4655165 ]]


In [53]:
b = np.ones((4, 3, 2))
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [57]:
a = np.array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [58]:
print(a[:2, :2])

[[1 2]
 [6 7]]
